'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Utils.EN", GetType(EN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Access Discord developpers space.
        '''</summary>
        Friend Shared ReadOnly Property AccessDeveloppersSpace() As String
            Get
                Return ResourceManager.GetString("AccessDeveloppersSpace", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Add.
        '''</summary>
        Friend Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Apply.
        '''</summary>
        Friend Shared ReadOnly Property Apply() As String
            Get
                Return ResourceManager.GetString("Apply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Change text.
        '''</summary>
        Friend Shared ReadOnly Property ChangeText() As String
            Get
                Return ResourceManager.GetString("ChangeText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Choose.
        '''</summary>
        Friend Shared ReadOnly Property Choose() As String
            Get
                Return ResourceManager.GetString("Choose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à To be able to use custom application, you must create it in the Discord developper space. An application can be used to : 
        '''  1. Be used to create Rich Presence in your game
        '''  2. Create a bot for a Discord server
        '''
        '''To access it, click the button below..
        '''</summary>
        Friend Shared ReadOnly Property CustomApp_Step1() As String
            Get
                Return ResourceManager.GetString("CustomApp_Step1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 1. Create the application.
        '''</summary>
        Friend Shared ReadOnly Property CustomApp_Step1Title() As String
            Get
                Return ResourceManager.GetString("CustomApp_Step1Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The client ID will be used to connect to the app to create the Rich Presence. With a custom app, you can: 
        '''    1. Personalize the title of rich presence
        '''    2. Personalize the images available for the Rich Presence
        '''
        '''Please copy and paste the client ID in the text box below:.
        '''</summary>
        Friend Shared ReadOnly Property CustomApp_Step2() As String
            Get
                Return ResourceManager.GetString("CustomApp_Step2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 2. Obtain client ID.
        '''</summary>
        Friend Shared ReadOnly Property CustomApp_Step2Title() As String
            Get
                Return ResourceManager.GetString("CustomApp_Step2Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The program is ready to be used with the application!.
        '''</summary>
        Friend Shared ReadOnly Property CustomApp_Step3() As String
            Get
                Return ResourceManager.GetString("CustomApp_Step3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 3. The program is ready!.
        '''</summary>
        Friend Shared ReadOnly Property CustomApp_Step3Title() As String
            Get
                Return ResourceManager.GetString("CustomApp_Step3Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Custom picture.
        '''</summary>
        Friend Shared ReadOnly Property CustomPicture() As String
            Get
                Return ResourceManager.GetString("CustomPicture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enter the image key:.
        '''</summary>
        Friend Shared ReadOnly Property CustomPictureInput() As String
            Get
                Return ResourceManager.GetString("CustomPictureInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Delete.
        '''</summary>
        Friend Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Don&apos;t save.
        '''</summary>
        Friend Shared ReadOnly Property DontSave() As String
            Get
                Return ResourceManager.GetString("DontSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à (empty).
        '''</summary>
        Friend Shared ReadOnly Property Empty() As String
            Get
                Return ResourceManager.GetString("Empty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Line 1.
        '''</summary>
        Friend Shared ReadOnly Property Line1() As String
            Get
                Return ResourceManager.GetString("Line1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enter text for the first line:.
        '''</summary>
        Friend Shared ReadOnly Property Line1Input() As String
            Get
                Return ResourceManager.GetString("Line1Input", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Line 2.
        '''</summary>
        Friend Shared ReadOnly Property Line2() As String
            Get
                Return ResourceManager.GetString("Line2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Enter text for second line:.
        '''</summary>
        Friend Shared ReadOnly Property Line2Input() As String
            Get
                Return ResourceManager.GetString("Line2Input", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;About.
        '''</summary>
        Friend Shared ReadOnly Property MNU_About() As String
            Get
                Return ResourceManager.GetString("MNU_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Custom apps.
        '''</summary>
        Friend Shared ReadOnly Property MNU_CustomApps() As String
            Get
                Return ResourceManager.GetString("MNU_CustomApps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Donate.
        '''</summary>
        Friend Shared ReadOnly Property MNU_Donate() As String
            Get
                Return ResourceManager.GetString("MNU_Donate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Exit.
        '''</summary>
        Friend Shared ReadOnly Property MNU_Exit() As String
            Get
                Return ResourceManager.GetString("MNU_Exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;File.
        '''</summary>
        Friend Shared ReadOnly Property MNU_File() As String
            Get
                Return ResourceManager.GetString("MNU_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;New.
        '''</summary>
        Friend Shared ReadOnly Property MNU_New() As String
            Get
                Return ResourceManager.GetString("MNU_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Open.
        '''</summary>
        Friend Shared ReadOnly Property MNU_Open() As String
            Get
                Return ResourceManager.GetString("MNU_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Re&amp;move.
        '''</summary>
        Friend Shared ReadOnly Property MNU_Remove() As String
            Get
                Return ResourceManager.GetString("MNU_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Rich Presence.
        '''</summary>
        Friend Shared ReadOnly Property MNU_RP() As String
            Get
                Return ResourceManager.GetString("MNU_RP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Save.
        '''</summary>
        Friend Shared ReadOnly Property MNU_Save() As String
            Get
                Return ResourceManager.GetString("MNU_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Sa&amp;ve as....
        '''</summary>
        Friend Shared ReadOnly Property MNU_SaveAs() As String
            Get
                Return ResourceManager.GetString("MNU_SaveAs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Updates.
        '''</summary>
        Friend Shared ReadOnly Property MNU_Updates() As String
            Get
                Return ResourceManager.GetString("MNU_Updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à &amp;Website.
        '''</summary>
        Friend Shared ReadOnly Property MNU_Website() As String
            Get
                Return ResourceManager.GetString("MNU_Website", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Name.
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à You have unsaved work.
        '''</summary>
        Friend Shared ReadOnly Property NotSaved_Caption() As String
            Get
                Return ResourceManager.GetString("NotSaved_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Do you wan&apos;t to save this RP?.
        '''</summary>
        Friend Shared ReadOnly Property NotSaved_InstructionText() As String
            Get
                Return ResourceManager.GetString("NotSaved_InstructionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Last modifications of this RP are not saved. Do You wan&apos;t to save it?.
        '''</summary>
        Friend Shared ReadOnly Property NotSaved_Text() As String
            Get
                Return ResourceManager.GetString("NotSaved_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Now.
        '''</summary>
        Friend Shared ReadOnly Property Now() As String
            Get
                Return ResourceManager.GetString("Now", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à OK.
        '''</summary>
        Friend Shared ReadOnly Property OK() As String
            Get
                Return ResourceManager.GetString("OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Past.
        '''</summary>
        Friend Shared ReadOnly Property Past() As String
            Get
                Return ResourceManager.GetString("Past", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Save and continue.
        '''</summary>
        Friend Shared ReadOnly Property SaveAndContinue() As String
            Get
                Return ResourceManager.GetString("SaveAndContinue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Save and exit.
        '''</summary>
        Friend Shared ReadOnly Property SaveAndExit() As String
            Get
                Return ResourceManager.GetString("SaveAndExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Open a file.
        '''</summary>
        Friend Shared ReadOnly Property SaveAndOpen_Caption() As String
            Get
                Return ResourceManager.GetString("SaveAndOpen_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à You are about to open another file. However, it is not registered. Would you like to save it before you continue?.
        '''</summary>
        Friend Shared ReadOnly Property SaveAndOpen_InstructionText() As String
            Get
                Return ResourceManager.GetString("SaveAndOpen_InstructionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à File unsaved.
        '''</summary>
        Friend Shared ReadOnly Property SaveAndOpen_Text() As String
            Get
                Return ResourceManager.GetString("SaveAndOpen_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Since.
        '''</summary>
        Friend Shared ReadOnly Property SinceTimestamp() As String
            Get
                Return ResourceManager.GetString("SinceTimestamp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
